Raise error when using query params in schema. (#7400)
Given schema:
```
  type User {
    required name: str {
      default := <str>$0;
    }
  }
```

The following error is produced:
```
error: query parameters are not allowed in schemas
  │
5 │           default := <str>$0;
  │                           ^^ error
```