Fix regression in restarting the management port (#1091)
Without this change the request crashes with:

   Error: __init__() missing 1 required positional argument: 'auto_shutdown'

This was introduced in 5161de72b.