Introduce edb.common.checked
Those data structures are supposed to replace edb.common.typed.  These are the
main selling points:

* they're fully type-annotated themselves;

* they are generic data structures enabling better annotating of other code;

* they use *that same generic syntax* to perform runtime checking; and

* the parametrized types don't have to be pre-declared on module level for the
  type to be picklable.

Example usage:

  >>> from edb.common.checked import CheckedList
  >>> cl = CheckedList[int]((1, 2, 3))
  >>> cl.append(4)
  >>> cl
  edb.common.checked.CheckedList[int]([1, 2, 3, 4])
  >>> cl.append("s")
  Traceback (most recent call last):
  ...
  ValueError: <class 'edb.common.checked.CheckedList[int]'> accepts only values of type <class 'int'>, got <class 'str'>