Check if type exists when tracing type cast, is, and introspect. (#7351)
Given the schema:
```
  type MyType {
    parent: MyType;
    is_initial := .parent is null;
  }
```

A nicer error is produced:
```
error: type 'default::null' does not exist
  │
6 │     is_initial := .parent is null;
  │                              ^^^^ Did you mean to use `exists`?
```