Add context to errors when casting to collections. (#7300)
If there is an incompatible element when casting to a collection, the `to` and `from` type are added as well as the name of the element.

For example, given the query `SELECT <tuple<a: array<tuple<b: int64>>>>(c:=[(d:=[1])]);`, the following error is produced:
```
error: QueryError: while casting 'tuple<c: array<tuple<d: array<std::int64>>>>' to 'tuple<a: array<tuple<b: std::int64>>>', at tuple element 'a', in array elements, at tuple element 'b', cannot cast 'array<std::int64>' to 'std::int64'
  ┌─ <query>:1:8
  │
1 │ SELECT <tuple<a: array<tuple<b: int64>>>>(c:=[(d:=[1])]);
  │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error
```