Improve syntax errors when a reserved keyword is used as an identifier (#3389)
With this improper use of reserved keywords will produce better errors,
e.g:

    edgedb> WITH select := '1' SELECT 1;
    error: EdgeQLSyntaxError: Unexpected keyword 'select'
      ┌─ query:1:6
      │
    1 │ WITH select := '1' SELECT 1;
      │      ^^^^^^ Use a different identifier or quote the name with backticks: `select`
      │
      = Token 'select' is a reserved keyword and cannot be used as an identifier