Catch aggregate calls in constraints and indexes in ql compiler (#7343)
- Catches aggregate calls in constraints and indexes earlier in the compilation process
    - Raises errors in migration create which were previously only caught on migrate
- Fixes abstract constraints not raising errors when using aggregate functions
- Adds more information in errors about aggregate functions

Given the schema:
```
  type User {
     name: str;
  }

  type HasTwoOrFewerUsers {
     users: User;
     constraint expression on (count(.users) <= 2);
  }
```

The following error is produced:
```
error: cannot use aggregate functions or operators in a non-aggregating constraint
   │
25 │      constraint expression on (count(.users) <= 2);
   │                                ^^^^^^^^^^^^^ error
```