Improve handling of references to non-existent schema items
Currently, a fairly nondescript error is raised when a bad reference to
a type is made in a query, and it also lacks proper source context.

  edgedb> SELECT Foo;
  InvalidReferenceError: reference to a non-existent schema item Foo

With this fix the error is much nicer:

  edgedb> SELECT Foo;
  InvalidReferenceError: object type or view 'Foo' does not exist
  ### SELECT Foo;
  ###        ^

Additionally, schema-level views of scalar types are now properly
supported.