Raise a more helpful error message for CONFIGURE DATABASE syntax.
Currently it just says "unexpected DATABASE" which is confusing.
Fix that by suggesting the correct syntax, as in:

   EdgeQLSyntaxError: 'CONFIGURE DATABASE' is invalid syntax.
   Did you mean 'CONFIGURE CURRENT DATABASE'?